travis:
  secure:
    BINSTAR_TOKEN: Moc9chAiObz1bbPH0OYHwy5uqjC7YIzfq1XqX7zewBjiyQNcl+UzKUvWL1/KIH1QffQly/WK/Qk0KHU74WtF1gTod+ILKL4d1Dn5IBhNlyiJ+znpwIRPpcnB9UIqibYO/AMhlPM1tfa2oIrTTH+5vG62n2A6qIQFr1rddd+5ubBL6m6R5SX1JGO93GNRz7itspQkJiNC08q5YERwtgSdDs/RzTo89sdIK2pzNq0vVWhMXkejAthilxTHYtLxbl1HAkSW27mWOjaDmkufL1N+N3oSUnQTRoK0mritHB5pB7ror83YkcDjFMK1Ugh5mEFlQ4S3+10q/mkLM2bFM6sqsb+/2d2+I0NawiTMhbHHSbivpVzQyelIVrqqIgJclFBVfLMnohMvo19oe6cpwwnLZvrLvMZnqhTdmVSg83xAu4cchyx7yWSS7pusb4t5f0CdfokHtvlOBNCQCSwHjs4e4rGs8WysiHJ6bKcL4B2WXtLILSMu5xNgqXgbcFpnq7dakJ6mvfO6xl8rqrSciTU+whkxWXHwx1rVIbcX5WXmsqeif93L5AepJkHyCfaAq4NDXm1co1nTDtMyoDhs1DuzqoyYYhs4K5L0pvDw8WUI+4HBq9dbARBSxnxBaYyefPAowdUCyAlK9mmxuc4zdGxTZiqm74kqxWulxsz9IrhmvbI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
