travis:
  secure:
    BINSTAR_TOKEN: NxDMhfCHebx3juSTo0znAnFPbQ6cvHL2p5Dr6gYhKEspmbMNY9egMCCSnerHfvqyUApDMngFciQehCd9SUfMpBNULMS5AcUvT29L8JqPBpbhMH3PtqM+KgXlfCwbf57OFqt0KyIIB/CLDzawVP2/NeXdBtkjgMWtotvZGw0A4zjGP9qweTm9aqaQDOp1qKAaJmcL9LDeUKSolipAGkgV3qapyHW6b9tds+mBoC5OrTWzhYma/XdmQT01B8i2hnxzFDbZrPSiyfMR+T6FNgMUOKuu4qPsroRve60O8yHzoywJQqhnUVfNYRA9L/TW9+PLVOHD+fXf0eTJDZxWEu5SRkpXtiaCmYOW0IwP/kUg51YnCQbW/AAcxzVUpf03qd6dk3hwLg3jN/e/GjjPzJ83X1IS8Xz/qUowkW7XzLZ0HCC9UfNgbonVlW7QL7HzcpEqDDhVAL4s3c9R1yUvQDy+puSAMZM/+NY+zpeHuCIYIlr5rqsJzgXZlaOZpqU3lkb4HpCby0qzZQ++9hhelOPb/v2CkPa4jR/TUSdnlnTjTuo7U/iflMWZ8FRzpe50tECUIRA4F9Q9d5fGiRCUz6neZ4G+5Zf7TT4cxWTDUY1oi4XJVI7Iim2pQ+iwNCIk7fMZLP6daZ6uNmnDykuwOC1Q+u1LS1Vctdoj94+3WQ0XNRE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
